;(function(window,Ployer){
	Ployer.data.defaultStyle = {
		"div":{
			"alignContent":"stretch",
			"alignItems":"stretch",
			"alignSelf":"stretch",
			"animation":"none 0s ease 0s 1 normal none running",
			"background":"none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0)",
			"baselineShift":"0px",
			"border":"0px none rgb(0, 0, 0)",
			"borderRadius":"0px",
			"borderCollapse":"separate",
			"borderSpacing":"0px",
			"boxSizing":"captionSide",
			"captionSide":"top",
			"clipRule":" nonzero",
		    "color":" rgb(0, 0, 0)",
		    "colorInterpolation":" sRGB",
		    "colorInterpolationFilters":" linearRGB",
		    "columnFill":" balance",
		    "columnRule":" 0px none rgb(0, 0, 0)",
		    "columns":" auto auto",
		    "cx":" 0px",
		    "cy":" 0px",
		    "direction":" ltr",
		    "emptyCells":" show",
		    "fill":" rgb(0, 0, 0)",
		    "fillOpacity":" 1",
		    "fillRule":" nonzero",
		    "flex":" 0 1 auto",
		    "flexFlow":" row nowrap",
		    "floodColor":" rgb(0, 0, 0)",
		    "floodOpacity":" 1",
		    "fontStyle":" normal",
		    "fontVariant":" normal",
		    "fontWeight":" normal",
		    "fontStretch":" normal",
		    "fontSize":" 16px",
		    "lineHeight":" normal",
		    "fontFamily":" STHeiti",
		    "justifyContent":" flexStart",
		    "lightingColor":" rgb(255, 255, 255)",
		    "listStyle":" disc outside none",
		    "margin":" 0px",
		    "maskType":" luminance",
		    "minHeight":" 0px",
		    "minWidth":" 0px",
		    "motion":" none 0px auto 0deg",
		    "objectFit":" fill",
		    "objectPosition":" 50% 50%",
		    "opacity":" 1",
		    "order":" 0",
		    "orphans":" 2",
		    "outline":" rgb(0, 0, 0) none 0px",
		    "outlineOffset":" 0px",
		    "overflow":" visible",
		    "padding":" 0px",
		    "paintOrder":" fill",
		    "perspectiveOrigin":" 50% 50%",
		    "position":" static",
		    "r":" 0px",
		    "shapeImageThreshold":" 0",
		    "shapeMargin":" 0px",
		    "stopColor":" rgb(0, 0, 0)",
		    "stopOpacity":" 1",
		    "strokeDashoffset":" 0px",
		    "strokeLinecap":" butt",
		    "strokeLinejoin":" miter",
		    "strokeMiterlimit":" 4",
		    "strokeOpacity":" 1",
		    "strokeWidth":" 1px",
		    "tabSize":" 8",
		    "textAlign":" start",
		    "textAnchor":" start",
		    "textIndent":" 0px",
		    "textOrientation":" mixed",
		    "textOverflow":" clip",
		    "transformOrigin":" 50% 50% 0px",
		    "transformStyle":" flat",
		    "transition":" all 0s ease 0s",
		    "userSelect":" text",
		    "verticalAlign":" baseline",
		    "visibility":" visible",
		    "widows":" 2",
		    "wordSpacing":" 0px",
		    "writingMode":" horizontalTb",
		    "x":" 0px",
		    "y":" 0px",
		    "zoom":" 1"
		}
	}
})(window,Ployer)